Task 1


In [27]:
import numpy as np
# Creates an array ranging values from 10 to 49
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 2


In [28]:
# Creates a 3x3 array ranging values from 0 to 8
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 3

In [72]:
# 3x3 identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 4

In [87]:
# Create a 3x3x3 array with random values
a = np.random.rand(3, 3, 3)
print(a)

[[[0.99875 0.19999 0.60294]
  [0.79937 0.87437 0.21821]
  [0.85582 0.24419 0.06571]]

 [[0.83942 0.344   0.71341]
  [0.18873 0.30688 0.79912]
  [0.42447 0.58574 0.84134]]

 [[0.32051 0.58989 0.92727]
  [0.69206 0.83881 0.76221]
  [0.49966 0.4281  0.78463]]]


Task 5

In [107]:
# Create a 10x10 array with random values and find the minimum and maximum values
a = np.random.rand(10, 10)
print(f"The maximum value: {a.max()}")
print(f"The minimum value: {a.min()}")

The maximum value: 0.9987006674065546
The minimum value: 0.012188040139078149


Task 6

In [130]:
# Create a random vector of size 30 and find the mean value
a = np.random.rand(30)
print("The mean value:", a.mean())

The mean value: 0.5285484562240083


Task 7

In [151]:
a = np.random.rand(5, 5)

# Normalize a 5x5 random matrix
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
print("The normalized value:\n", normalized)

The normalized value:
 [[0.33318 0.71538 0.66343 1.      0.31813]
 [0.39616 0.      0.68942 0.12059 0.59911]
 [0.90721 0.91958 0.64958 0.48054 0.01888]
 [0.75394 0.64847 0.69065 0.15632 0.044  ]
 [0.41416 0.00132 0.64696 0.99599 0.50059]]


Task 8

In [156]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]).reshape(5, 3)
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
result = a @ b
print("The real matrix product:\n", result)

The real matrix product:
 [[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


Task 9

In [157]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = a @ b
print("The dot product:\n", result)

The dot product:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Task 10

In [161]:
# Create two 3x3 matrices and compute their dot product
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("The transpose:\n", a.transpose())

The transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


Task 11

In [162]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The determinant of the array:\n", np.linalg.det(a))

The determinant of the array:
 -9.51619735392994e-16


Task 12

In [168]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("The dot product:\n", np.dot(a, b))

The dot product:
 [[ 70  80  90]
 [158 184 210]
 [246 288 330]]


Task 13

In [169]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1], [2], [3]])
result = a @ b
print("The dot product:\n", result)

The dot product:
 [[14]
 [32]
 [50]]


Task 14

In [170]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1], [2], [3]])
x = np.linalg.solve(a, b)
print("The solution:\n", x)

The solution:
 [[-0.33333]
 [ 0.66667]
 [ 0.     ]]


Task 15

In [172]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
row_sums = a.sum(axis=1)
column_sums = a.sum(axis=0)
print("The row wise sum:\n", row_sums)
print("The column wise sum:\n", column_sums)

The row wise sum:
 [ 15  40  65  90 115]
The column wise sum:
 [55 60 65 70 75]
